### ISSUE TITLE
Update Required: Not functional with new fluentvalidation version

### ISSUE THREAD

**Issue by JWilh** [iron9light/FluentValidation.Extensions#4]
Hi,

with the new fluentvalidation version 10.x the package is no longer functional:
System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<FluentValidation.Results.ValidationFailure> FluentValidation.Results.ValidationResult.get_Errors()'.
   at IL.FluentValidation.Extensions.Options.FluentValidationValidateOptions`1.Validate(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   
On the release page for fluent validators: [Fluent validation releases](https://github.com/FluentValidation/FluentValidation/releases)
Changes in 10.0.0
Changed type of ValidationResult.Errors from IList<ValidationFailure> to List<ValidationFailure>

Would it be possible to update this package to work with the new version?

Thanks in advance

**Comment by iron9light** [comment]
I c.
<https://docs.fluentvalidation.net/en/latest/upgrading-to-10.html#validationresult-errors-type-change>

I wonder why they do that?

**Comment by JWilh** [comment]
I actually don't know, what's a good reason for it, but thanks for updating the library, it's working fine :-)
